<section class="ao-site-content ao-service-landing-page"><div class="ao-content-shell">
  <div class="ao-content-hero"><span class="ao-content-kicker">Ahost SiteBuilder</span><h1>Kod yazmadan premium web siteleri oluşturun.</h1><p>Ajanslar, işletmeler ve müşteriler için sürükle-bırak sayfa üretimi, hazır bloklar, SEO alanları, export ve yayınlama akışı.</p><div class="ao-content-actions"><a class="ao-content-btn" href="<?= url('sitebuilder/preview-public') ?>">SiteBuilder Dene</a><a class="ao-content-btn secondary" href="<?= url('marketplace') ?>">Hazır Temalar</a><a class="ao-content-btn secondary" href="<?= url('teklif') ?>">Teklif Al</a></div></div>
  <div class="ao-content-grid two">
      <article class="ao-content-card ao-service-card"><div class="ao-content-list-icon">🎨</div><h3>Sürükle Bırak</h3><p>Sayfa, bölüm, kolon ve hazır bloklarla hızlı site üretimi.</p><a class="ao-content-btn secondary" href="<?= url('sitebuilder/create-demo') ?>">Demo oluştur →</a></article>
      <article class="ao-content-card ao-service-card"><div class="ao-content-list-icon">🚀</div><h3>Yayınlama Akışı</h3><p>Önizleme, düzenleme, dışa aktarma ve müşteri teslim süreçleri.</p><a class="ao-content-btn secondary" href="<?= url('sitebuilder/preview-public') ?>">Önizle →</a></article>
      <article class="ao-content-card ao-service-card"><div class="ao-content-list-icon">🔍</div><h3>SEO Hazır</h3><p>Başlık, açıklama, sitemap ve hızlı sayfa yapısı.</p><a class="ao-content-btn secondary" href="<?= url('web-tasarim') ?>">Web tasarım hizmeti →</a></article>
      <article class="ao-content-card ao-service-card"><div class="ao-content-list-icon">💰</div><h3>Teklif Alın</h3><p>Özel web sitesi için hemen teklif alın.</p><a class="ao-content-btn secondary" href="<?= url('teklif') ?>">Teklif Talep Et →</a></article>
  </div>
  <div class="ao-content-cta"><h2>Projenizi Ahost One ekosistemine taşıyın</h2><p>Domain, hosting, ürün, teklif, müşteri paneli ve destek süreçleri aynı tasarım diliyle çalışır.</p><div class="ao-content-actions"><a class="ao-content-btn" href="<?= url('teklif') ?>">Teklif Al</a><a class="ao-content-btn secondary" href="<?= url('urunler') ?>">Ürünleri Gör</a></div></div>
</div></section>