<?php require __DIR__.'/_helpers.php'; $flash=get_flash(); ?>
<?php if($flash): ?><div class="ao-alert <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<div class="ao-hero-slim"><div class="cp-page-head"><div><h2>Ayarlar Merkezi</h2><p>Bütün ayarlar aynı sayfada sekmeli olarak düzenlenir; başka sayfaya yönlendirme yapılmaz.</p></div><a class="ao-btn" href="<?= url('admin/setup-wizard') ?>">Kurulum Sihirbazı</a></div></div>
<div class="ao-card settings-inline-panel" data-ao-tabs>
  <?php $tabs=['general'=>'Genel','local'=>'Yerelleştirme','orders'=>'Sipariş','domain'=>'Domain','smtp'=>'SMTP','finance'=>'Finans','security'=>'Güvenlik','notifications'=>'Bildirimler','support'=>'Destek','social'=>'Sosyal Medya','ai'=>'AI Center','sitebuilder'=>'SiteBuilder','mobilebuilder'=>'MobileBuilder','marketplace'=>'Marketplace','license'=>'Lisans']; ?>
  <div class="ao-panel-tabs"><?php $i=0; foreach($tabs as $key=>$label): ?><button type="button" class="<?= $i++===0?'active':'' ?>" data-ao-tab="<?= e($key) ?>"><?= e($label) ?></button><?php endforeach; ?></div>
  <form method="post" action="<?= url('admin/settings/save') ?>" class="ao-form"><?= csrf_field() ?><input type="hidden" name="section" value="inline">
  <section class="ao-panel active" data-ao-panel="general"><h3>Genel</h3><div class="ao-form-grid"><label>Site Adı<input name="settings[site_name]" value="<?= e(admin_setting('site_name','Ahost One')) ?>"></label><label>Site URL<input name="settings[site_url]" value="<?= e(admin_setting('site_url',url(''))) ?>"></label><label>Logo URL<input name="settings[logo_url]" value="<?= e(admin_setting('logo_url','')) ?>"></label><label>Admin E-posta<input name="settings[admin_email]" value="<?= e(admin_setting('admin_email','')) ?>"></label></div></section>
  <section class="ao-panel" data-ao-panel="local"><h3>Yerelleştirme</h3><div class="ao-form-grid"><label>Varsayılan Dil<select name="settings[default_language]"><option value="tr">Türkçe</option><option value="en">English</option></select></label><label>Para Birimi<select name="settings[default_currency]"><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Kur Gösterimi<input name="settings[usd_try_text]" value="<?= e(admin_setting('usd_try_text','1 $ = 47.25 TL')) ?>"></label><label>Tarih Formatı<input name="settings[date_format]" value="<?= e(admin_setting('date_format','d.m.Y')) ?>"></label></div></section>
  <section class="ao-panel" data-ao-panel="orders"><h3>Sipariş</h3><div class="ao-form-grid"><label>Sipariş Onayı<select name="settings[order_approval]"><option value="auto">Otomatik</option><option value="manual">Manuel</option></select></label><label>Sepet Hatırlatma<select name="settings[cart_reminder_enabled]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label><label>Minimum Sepet<input name="settings[min_cart_total]" value="<?= e(admin_setting('min_cart_total','0')) ?>"></label></div></section>
  <section class="ao-panel" data-ao-panel="domain"><h3>Domain</h3><div class="ao-form-grid"><label>Varsayılan Registrar<select name="settings[default_registrar]"><option value="domainnameapi">DomainNameAPI</option><option value="resellerclub">ResellerClub</option></select></label><label>DomainNameAPI Kullanıcı<input name="settings[domainnameapi_username]" value="<?= e(admin_setting('domainnameapi_username','')) ?>"></label><label>DomainNameAPI Şifre/API Key<input name="settings[domainnameapi_password]" value="<?= e(admin_setting('domainnameapi_password','')) ?>"></label><label>Belge isteyen TLD'ler<textarea name="settings[document_required_tlds]" placeholder="com.tr,av.tr,dr.tr"><?= e(admin_setting('document_required_tlds','com.tr,av.tr,dr.tr')) ?></textarea></label></div></section>
  <section class="ao-panel" data-ao-panel="smtp"><h3>SMTP / SMS</h3><div class="ao-form-grid"><label>SMTP Host<input name="settings[smtp_host]" value="<?= e(admin_setting('smtp_host','')) ?>"></label><label>SMTP Port<input name="settings[smtp_port]" value="<?= e(admin_setting('smtp_port','587')) ?>"></label><label>SMTP Kullanıcı<input name="settings[smtp_user]" value="<?= e(admin_setting('smtp_user','')) ?>"></label><label>SMTP Şifre<input name="settings[smtp_pass]" value="<?= e(admin_setting('smtp_pass','')) ?>"></label><label>İletiMerkezi API Key<input name="settings[iletimerkezi_api_key]" value="<?= e(admin_setting('iletimerkezi_api_key','')) ?>"></label><label>İletiMerkezi Hash<input name="settings[iletimerkezi_api_hash]" value="<?= e(admin_setting('iletimerkezi_api_hash','')) ?>"></label></div></section>
  <section class="ao-panel" data-ao-panel="finance"><h3>Finans</h3><div class="ao-form-grid"><label>Shopier PAT<textarea name="settings[shopier_pat]" rows="4"><?= e(admin_setting('shopier_pat','')) ?></textarea></label><label>KDV Oranı<input name="settings[vat_rate]" value="<?= e(admin_setting('vat_rate','20')) ?>"></label><label>Komisyon Oranı<input name="settings[payment_fee_percent]" value="<?= e(admin_setting('payment_fee_percent','0')) ?>"></label></div></section>
  <section class="ao-panel" data-ao-panel="security"><h3>Güvenlik</h3><div class="ao-form-grid">
    <label>Admin 2FA Politikası<select name="settings[admin_mfa_policy]"><option value="off" <?= admin_setting('admin_mfa_policy','optional')==='off'?'selected':'' ?>>Kapalı</option><option value="optional" <?= admin_setting('admin_mfa_policy','optional')==='optional'?'selected':'' ?>>İsteğe Bağlı</option><option value="required" <?= admin_setting('admin_mfa_policy','optional')==='required'?'selected':'' ?>>Zorunlu</option></select></label>
    <label>Müşteri 2FA Politikası<select name="settings[customer_mfa_policy]"><option value="off" <?= admin_setting('customer_mfa_policy','optional')==='off'?'selected':'' ?>>Kapalı</option><option value="optional" <?= admin_setting('customer_mfa_policy','optional')==='optional'?'selected':'' ?>>İsteğe Bağlı</option><option value="required" <?= admin_setting('customer_mfa_policy','optional')==='required'?'selected':'' ?>>Zorunlu</option></select></label>
    <label>Varsayılan Yöntem<select name="settings[mfa_default_method]"><option value="mail" <?= admin_setting('mfa_default_method','mail')==='mail'?'selected':'' ?>>Mail OTP</option><option value="totp" <?= admin_setting('mfa_default_method','mail')==='totp'?'selected':'' ?>>Google Authenticator</option><option value="sms" <?= admin_setting('mfa_default_method','mail')==='sms'?'selected':'' ?>>SMS OTP</option></select></label>
    <label>Mail OTP<select name="settings[mfa_mail_enabled]"><option value="1" <?= admin_setting('mfa_mail_enabled','1')==='1'?'selected':'' ?>>Aktif</option><option value="0" <?= admin_setting('mfa_mail_enabled','1')==='0'?'selected':'' ?>>Pasif</option></select></label>
    <label>Google Authenticator<select name="settings[mfa_totp_enabled]"><option value="1" <?= admin_setting('mfa_totp_enabled','1')==='1'?'selected':'' ?>>Aktif</option><option value="0" <?= admin_setting('mfa_totp_enabled','1')==='0'?'selected':'' ?>>Pasif</option></select></label>
    <label>SMS OTP<select name="settings[mfa_sms_enabled]"><option value="0" <?= admin_setting('mfa_sms_enabled','0')==='0'?'selected':'' ?>>Pasif</option><option value="1" <?= admin_setting('mfa_sms_enabled','0')==='1'?'selected':'' ?>>Aktif</option></select></label>
    <label>OTP Süresi (dakika)<input name="settings[mfa_otp_ttl_minutes]" value="<?= e(admin_setting('mfa_otp_ttl_minutes','5')) ?>"></label>
    <label>Maksimum Deneme<input name="settings[mfa_max_attempts]" value="<?= e(admin_setting('mfa_max_attempts','5')) ?>"></label>
    <label>SMS Gönderici<input name="settings[mfa_sms_sender]" value="<?= e(admin_setting('mfa_sms_sender','AhostOne')) ?>"></label>
    <label>reCAPTCHA Site Key<input name="settings[recaptcha_site_key]" value="<?= e(admin_setting('recaptcha_site_key','')) ?>"></label>
    <label>IP Whitelist<textarea name="settings[ip_whitelist]"><?= e(admin_setting('ip_whitelist','')) ?></textarea></label>
  </div><p class="muted">Mail OTP, Google Authenticator/TOTP ve SMS OTP yöntemleri admin ve müşteri girişlerinde ayrı politikalarla yönetilir.</p></section>
  <section class="ao-panel" data-ao-panel="notifications"><h3>Bildirimler</h3><div class="ao-form-grid"><label>Mail Bildirimi<select name="settings[notify_email_enabled]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label><label>SMS Bildirimi<select name="settings[notify_sms_enabled]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label><label>WhatsApp Bildirimi<select name="settings[notify_whatsapp_enabled]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label></div></section>
  <section class="ao-panel" data-ao-panel="support"><h3>Destek</h3><div class="ao-form-grid"><label>WhatsApp Numarası<input name="settings[support_whatsapp_number]" value="<?= e(admin_setting('support_whatsapp_number','')) ?>"></label><label>Arama Numarası<input name="settings[support_call_number]" value="<?= e(admin_setting('support_call_number','')) ?>"></label><label>AI Destek<select name="settings[support_ai_enabled]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label><label>Çalışma Saatleri<input name="settings[support_hours]" value="<?= e(admin_setting('support_hours','09:00-18:00')) ?>"></label></div></section>
  <section class="ao-panel" data-ao-panel="social"><h3>Sosyal Medya</h3><div class="ao-form-grid"><label>Facebook<input name="settings[social_facebook]"></label><label>Instagram<input name="settings[social_instagram]"></label><label>X / Twitter<input name="settings[social_x]"></label><label>LinkedIn<input name="settings[social_linkedin]"></label><label>YouTube<input name="settings[social_youtube]"></label><label>TikTok<input name="settings[social_tiktok]"></label></div></section>
  <section class="ao-panel" data-ao-panel="ai"><h3>AI Center</h3><div class="ao-form-grid"><label>OpenAI API Key<input name="settings[openai_api_key]" value="<?= e(admin_setting('openai_api_key','')) ?>"></label><label>Gemini API Key<input name="settings[gemini_api_key]" value="<?= e(admin_setting('gemini_api_key','')) ?>"></label><label>Claude API Key<input name="settings[claude_api_key]" value="<?= e(admin_setting('claude_api_key','')) ?>"></label><label>Varsayılan Sağlayıcı<select name="settings[default_ai_provider]"><option>openai</option><option>gemini</option><option>claude</option><option>openrouter</option></select></label></div></section>
  <section class="ao-panel" data-ao-panel="sitebuilder"><h3>SiteBuilder</h3><div class="ao-form-grid"><label>AI ile Düzenle<select name="settings[sitebuilder_ai_edit]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label><label>ZIP Export<select name="settings[sitebuilder_zip_export]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label></div></section>
  <section class="ao-panel" data-ao-panel="mobilebuilder"><h3>MobileBuilder</h3><div class="ao-form-grid"><label>AI ile Düzenle<select name="settings[mobilebuilder_ai_edit]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label><label>Build Queue<select name="settings[mobilebuilder_build_queue]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label></div></section>
  <section class="ao-panel" data-ao-panel="marketplace"><h3>Marketplace</h3><div class="ao-form-grid"><label>Komisyon %<input name="settings[marketplace_commission]" value="<?= e(admin_setting('marketplace_commission','10')) ?>"></label><label>Escrow<select name="settings[marketplace_escrow_enabled]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label></div></section>
  <section class="ao-panel" data-ao-panel="license"><h3>Lisans</h3><div class="ao-form-grid"><label>Trial Lisans<select name="settings[trial_license_enabled]"><option value="1">Aktif</option><option value="0">Pasif</option></select></label><label>Varsayılan Trial Gün<input name="settings[trial_days]" value="<?= e(admin_setting('trial_days','14')) ?>"></label></div></section>
  <div class="ao-action-row" style="margin-top:18px"><button class="ao-btn">Tüm Ayarları Kaydet</button><button class="ao-btn soft" type="submit" name="test" value="1">Kaydet ve Test Et</button></div>
  </form>
</div>
