
(function(){
  const $=(s,ctx=document)=>ctx.querySelector(s); const $$=(s,ctx=document)=>Array.from(ctx.querySelectorAll(s));
  const state={sections:[], selected:null, history:[], future:[]};
  const elCanvas=()=>$('#sbCanvas'); const jsonInput=()=>$('#builder_json');
  function uid(){return 'sb_'+Math.random().toString(36).slice(2,10)}
  function snapshot(){state.history.push(JSON.stringify(state.sections)); if(state.history.length>60) state.history.shift(); state.future=[]}
  function load(){try{const raw=jsonInput()?.value||''; if(raw) state.sections=JSON.parse(raw)}catch(e){state.sections=[]} if(!state.sections.length){state.sections=[section('hero')]} render()}
  function section(type='section',cols=1){let content=[]; if(type==='hero') content=[elem('heading','Ahost One ile güçlü dijital platform'),elem('text','Domain, hosting, marketplace ve builder çözümleri tek panelde.'),elem('button','Teklif Al')]; return {id:uid(),type,cols,content}}
  function elem(type,text=''){return {id:uid(),type,text:text||defaults[type]||type,props:{}}}
  const defaults={heading:'Başlık metni',text:'Paragraf metni',button:'Buton',image:'https://placehold.co/900x420',video:'https://www.youtube.com/embed/dQw4w9WgXcQ',form:'İletişim Formu',slider:'Slider',gallery:'Galeri',price:'Fiyat Tablosu',map:'Harita'};
  function render(){const c=elCanvas(); if(!c)return; c.innerHTML=''; state.sections.forEach(sec=>c.appendChild(renderSection(sec))); if(jsonInput()) jsonInput().value=JSON.stringify(state.sections);}
  function renderSection(sec){const d=document.createElement('div'); d.className='sb-section '+(state.selected===sec.id?'active':''); d.dataset.id=sec.id; d.innerHTML='<div class="sb-actions"><button type="button" class="sb-mini" data-act="clone-sec">Kopya</button><button type="button" class="sb-mini" data-act="del-sec">Sil</button></div>';
    const row=document.createElement('div'); row.className='sb-row sb-cols-'+(sec.cols||1); for(let i=0;i<(sec.cols||1);i++){const col=document.createElement('div'); col.className='sb-col'; const items=(i===0?sec.content:[]); items.forEach(e=>col.appendChild(renderElem(e))); row.appendChild(col)} d.appendChild(row); return d;}
  function renderElem(e){const d=document.createElement('div'); d.className='sb-element '+(state.selected===e.id?'active':''); d.dataset.id=e.id; let html=''; if(e.type==='heading') html='<h2>'+esc(e.text)+'</h2>'; else if(e.type==='text') html='<p>'+esc(e.text)+'</p>'; else if(e.type==='button') html='<a class="ao-btn" href="#">'+esc(e.text)+'</a>'; else if(e.type==='image') html='<img src="'+esc(e.text)+'" style="max-width:100%;border-radius:14px">'; else if(e.type==='form') html='<form><input placeholder="Ad Soyad"><input placeholder="E-posta"><button type="button">Gönder</button></form>'; else if(e.type==='price') html='<div class="ao-card"><h3>Başlangıç</h3><strong>₺499</strong><p>Temel paket</p></div>'; else html='<div>'+esc(e.text)+'</div>'; d.innerHTML=html+'<div class="sb-actions"><button type="button" class="sb-mini" data-act="clone-el">Kopya</button><button type="button" class="sb-mini" data-act="del-el">Sil</button></div>'; return d;}
  function esc(s){return String(s||'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
  function findElement(id){for(const s of state.sections){if(s.id===id)return {section:s,element:null}; const e=s.content.find(x=>x.id===id); if(e)return {section:s,element:e}} return null}
  function inspect(id){state.selected=id; render(); const box=$('#sbInspectorFields'); if(!box)return; const f=findElement(id); if(!f){box.innerHTML='<p>Bir öğe seçin.</p>';return} if(f.element){box.innerHTML='<div class="sb-field"><label>Tip</label><input value="'+esc(f.element.type)+'" readonly></div><div class="sb-field"><label>İçerik / URL</label><textarea id="sbText">'+esc(f.element.text)+'</textarea></div><button type="button" class="ao-btn" id="sbApplyText">Uygula</button>'; $('#sbApplyText').onclick=()=>{snapshot(); f.element.text=$('#sbText').value; render(); inspect(f.element.id)}} else {box.innerHTML='<div class="sb-field"><label>Kolon</label><select id="sbCols"><option>1</option><option>2</option><option>3</option><option>4</option></select></div><button type="button" class="ao-btn" id="sbApplySec">Uygula</button>'; $('#sbCols').value=f.section.cols||1; $('#sbApplySec').onclick=()=>{snapshot(); f.section.cols=parseInt($('#sbCols').value); render(); inspect(f.section.id)}}}
  document.addEventListener('click',e=>{const widget=e.target.closest('[data-widget]'); if(widget){snapshot(); state.sections[state.sections.length-1].content.push(elem(widget.dataset.widget)); render(); return}
    const addSec=e.target.closest('[data-add-section]'); if(addSec){snapshot(); state.sections.push(section('section',parseInt(addSec.dataset.addSection))); render(); return}
    const act=e.target.closest('[data-act]'); if(act){const box=act.closest('.sb-element,.sb-section'); const id=box?.dataset.id; const f=findElement(id); if(!f)return; snapshot(); if(act.dataset.act==='del-sec') state.sections=state.sections.filter(s=>s.id!==id); if(act.dataset.act==='clone-sec') state.sections.push(JSON.parse(JSON.stringify({...f.section,id:uid()}))); if(act.dataset.act==='del-el') f.section.content=f.section.content.filter(x=>x.id!==id); if(act.dataset.act==='clone-el') f.section.content.push({...f.element,id:uid()}); render(); return}
    const sel=e.target.closest('.sb-element,.sb-section'); if(sel&&elCanvas()?.contains(sel)){inspect(sel.dataset.id)} });
  document.addEventListener('click',e=>{if(e.target.id==='sbUndo'){if(state.history.length){state.future.push(JSON.stringify(state.sections)); state.sections=JSON.parse(state.history.pop()); render()}} if(e.target.id==='sbRedo'){if(state.future.length){state.history.push(JSON.stringify(state.sections)); state.sections=JSON.parse(state.future.pop()); render()}}});
  document.addEventListener('DOMContentLoaded',load);
})();
