<?php
ao_v2450_ensure_showcase_schema(); $rows=[];
try{$rows=db()->query('SELECT * FROM portfolio_references WHERE is_active=1 ORDER BY is_featured DESC,sort_order,id')->fetchAll() ?: [];}catch(Throwable $e){}
$cats=['all'=>'Tümü','website'=>'Web Siteleri','android'=>'Android','ios'=>'iOS','ecommerce'=>'E-Ticaret','corporate'=>'Kurumsal'];
function ao_reference_cards_v2464($items){ foreach($items as $r): $type=$r['reference_type'] ?: 'website'; $cover=trim((string)($r['cover_image_url'] ?: $r['image_url'] ?: 'public/assets/img/placeholder-product.svg')); $logo=trim((string)($r['logo_url'] ?? '')); ?>
  <article class="ref-card" data-ref-type="<?= e($type) ?>" data-ref-sector="<?= e(mb_strtolower((string)($r['sector']??''),'UTF-8')) ?>">
    <div class="ref-cover <?= e($type) ?>" style="background-image:url('<?= e(url($cover)) ?>')"><span><?= $type==='android'?'Android':'Web' ?></span></div>
    <div class="ref-body">
      <?php if($logo): ?><img class="ref-logo" src="<?= e(url($logo)) ?>" alt="<?= e($r['title'] ?? '') ?> logo"><?php endif; ?>
      <small><?= e($r['sector'] ?? '') ?></small><h3><?= e($r['title'] ?? '') ?></h3><p><?= e($r['short_description'] ?? '') ?></p><div class="ref-tech"><?= e($r['technologies'] ?? '') ?></div><?php if(!empty($r['project_url'])): ?><a target="_blank" rel="noopener" href="<?= e($r['project_url']) ?>">Projeyi İncele →</a><?php endif; ?></div>
  </article>
<?php endforeach; }

?>
<section class="ref-page">
  <header class="ref-hero"><span>Seçili Çalışmalar</span><h1>Fikirleri çalışan dijital ürünlere dönüştürüyoruz.</h1><p>Web siteleri ve Android uygulamalarını kategorilerle yan yana keşfedin; sayfa aşağı kaymadan filtreleyin.</p><div><a class="site-btn" href="<?= url('client/register') ?>">Projenizi Başlatın</a><a class="site-btn secondary" href="<?= url('urunler') ?>">Çözümleri İnceleyin</a></div></header>
  <nav class="ref-tabs" aria-label="Referans kategorileri"><?php foreach($cats as $k=>$label): ?><a href="#" class="ref-tab <?= $k==='all'?'is-active':'' ?>" data-ref-filter="<?= e($k) ?>"><?= e($label) ?></a><?php endforeach; ?></nav>
  <div class="ref-grid" data-ref-grid><?php ao_reference_cards_v2464($rows); ?></div>
</section>
<script>document.addEventListener('click',function(e){var t=e.target.closest('[data-ref-filter]'); if(!t)return; e.preventDefault(); var f=t.dataset.refFilter; document.querySelectorAll('[data-ref-filter]').forEach(function(x){x.classList.toggle('is-active',x===t)}); var grid=document.querySelector('[data-ref-grid]'); if(!grid)return; grid.classList.toggle('is-filtered',f!=='all'); grid.querySelectorAll('.ref-card').forEach(function(card){var ok=f==='all'||card.dataset.refType===f||(f==='ecommerce'&&(card.dataset.refSector||'').includes('ticaret'))||(f==='corporate'&&(card.dataset.refSector||'').includes('kurumsal')); card.classList.toggle('is-visible',ok);});});</script>
<style>.ref-page{max-width:1240px;margin:auto;padding:42px 24px 80px}.ref-hero{padding:68px clamp(24px,6vw,76px);border-radius:30px;background:linear-gradient(135deg,#071426,#14233d);color:#fff;margin-bottom:28px}.ref-hero>span{font-size:12px;font-weight:900;letter-spacing:.14em;text-transform:uppercase;color:#60a5fa}.ref-hero h1{max-width:820px;font-size:clamp(36px,6vw,68px);line-height:1.02;margin:14px 0 18px}.ref-hero p{max-width:720px;color:#cbd5e1;font-size:18px;line-height:1.7}.ref-hero div{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.ref-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.ref-card{overflow:hidden;border:1px solid #e2e8f0;border-radius:22px;background:#fff;box-shadow:0 12px 36px rgba(15,23,42,.07);transition:.2s}.ref-card:hover{transform:translateY(-4px);box-shadow:0 20px 44px rgba(15,23,42,.12)}.ref-cover{height:190px;background:linear-gradient(135deg,#dbeafe,#ede9fe);background-size:cover;background-position:center;padding:16px}.ref-cover.android{background:linear-gradient(135deg,#dcfce7,#dbeafe)}.ref-cover span{display:inline-flex;padding:7px 10px;border-radius:999px;background:rgba(255,255,255,.88);font-size:11px;font-weight:900;text-transform:uppercase}.ref-body{padding:20px;position:relative}.ref-logo{width:54px;height:54px;border-radius:16px;object-fit:cover;border:4px solid #fff;box-shadow:0 12px 24px rgba(15,23,42,.14);margin-top:-48px;background:#fff;display:block;margin-bottom:10px}.ref-body small{color:#2563eb;font-weight:800}.ref-body h3{font-size:20px;margin:7px 0 10px}.ref-body p{color:#64748b;line-height:1.6;min-height:70px}.ref-tech{font-size:12px;font-weight:800;color:#475569;border-top:1px solid #eef2f7;padding-top:14px;margin-top:14px}.ref-body a{display:inline-block;margin-top:14px;font-weight:900;text-decoration:none}@media(max-width:1100px){.ref-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.ref-page{padding:22px 14px 60px}.ref-hero{padding:38px 22px;border-radius:22px}.ref-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.ref-grid{grid-template-columns:1fr}.ref-body p{min-height:0}}</style>
