</section></main></div><!-- customer-shell --><script src="<?= url('public/assets/js/customer/panel.js') ?>?v=24.5.0"></script>
<script src="<?= url('public/assets/js/domain-popup.js') ?>?v=24.5.0"></script><script id="ao-currency-live-v186">
(function(){
 const rate=parseFloat(document.querySelector('.fx-rate')?.textContent?.match(/[0-9]+(?:\.[0-9]+)?/)?.[0]||'45');
 const fmt=(v,c)=>c==='USD'?'$'+(v/rate).toFixed(2):'₺'+Number(v).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});
 function apply(cur){localStorage.setItem('ao_currency',cur);document.querySelectorAll('#aoCurrency').forEach(s=>s.value=cur);document.querySelectorAll('[data-price-base]').forEach(el=>{let base=parseFloat(el.dataset.priceBase||'0');el.textContent=fmt(base,cur);el.classList.add('pulse');setTimeout(()=>el.classList.remove('pulse'),220);});}
 document.querySelectorAll('#aoCurrency').forEach(s=>{s.value=localStorage.getItem('ao_currency')||'TRY';s.addEventListener('change',()=>apply(s.value));}); apply(localStorage.getItem('ao_currency')||'TRY');
})();</script><?php if (function_exists('current_admin') && current_admin()): $bp=ao_builder_context_from_route(trim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), '/')); ?>
<div class="ao-floating-edit"><details><summary>✏ <span class="ao-fab-label">Düzenle</span></summary><div class="ao-floating-edit-menu"><small><?= e(strtoupper($bp['target'].' / '.$bp['template'])) ?></small><a href="#" class="ao-inline-edit-start">Bu sayfayı düzenle</a><a href="<?= url('admin/theme-center/editor') ?>">Tema düzenle</a><a href="<?= url('admin/builder-pro?target='.$bp['target'].'&template='.$bp['template'].'&device=mobile') ?>">Mobil görünüm</a><a href="<?= url('admin/theme-center/themes') ?>">Temalar</a></div></details></div>
<?php endif; ?><nav class="mobile-bottom-nav"><a class="mobile-nav-item<?= ao_mobile_nav_active_class('home') ?>" href="<?= url('') ?>"><b>⌂</b>Ana</a><a class="mobile-nav-item<?= ao_mobile_nav_active_class('domain') ?>" href="<?= url('domain') ?>"><b>🌐</b>Domain</a><a class="mobile-nav-item<?= ao_mobile_nav_active_class('package') ?>" href="<?= url('hosting') ?>"><b>📦</b>Paket</a><a class="mobile-nav-item<?= ao_mobile_nav_active_class('support') ?>" href="<?= url('client/support') ?>"><b>🎧</b>Destek</a><a class="mobile-nav-item<?= ao_mobile_nav_active_class('panel') ?>" href="<?= url('client') ?>"><b>👤</b>Panel</a></nav><script src="<?= url('public/assets/js/inline-builder-v1881.js') ?>?v=24.5.0"></script><script src="<?= url('public/assets/js/front/mobile-cleanup-v2416.js') ?>?v=24.5.0"></script></body></html>