<section class="ao-site-content ao-service-landing-page"><div class="ao-content-shell">
  <div class="ao-content-hero"><span class="ao-content-kicker">Ahost MobileBuilder</span><h1>Mobil uygulamanızı tek panelden oluşturun.</h1><p>Android/PWA uygulama oluşturma, menü, bottom bar, CTA, push bildirim ve build kuyruğu için merkezi MobileBuilder deneyimi.</p><div class="ao-content-actions"><a class="ao-content-btn" href="<?= url('mobilebuilder/preview-public') ?>">MobileBuilder Dene</a><a class="ao-content-btn secondary" href="<?= url('mobil-uygulama') ?>">Mobil Hizmetleri Gör</a><a class="ao-content-btn secondary" href="<?= url('teklif') ?>">Teklif Al</a></div></div>
  <div class="ao-content-grid two">
      <article class="ao-content-card ao-service-card"><div class="ao-content-list-icon">📱</div><h3>Android / PWA</h3><p>Mobil uygulama tasarımı, APK/AAB hazırlığı ve yayın akışı.</p><a class="ao-content-btn secondary" href="<?= url('mobilebuilder/create-demo') ?>">Demo oluştur →</a></article>
      <article class="ao-content-card ao-service-card"><div class="ao-content-list-icon">🔔</div><h3>Push & Menü</h3><p>Bildirim, mobil menü, alt bar ve hızlı aksiyon yönetimi.</p><a class="ao-content-btn secondary" href="<?= url('mobilebuilder/preview-public') ?>">Önizle →</a></article>
      <article class="ao-content-card ao-service-card"><div class="ao-content-list-icon">🧩</div><h3>Lisanslı Teslim</h3><p>MobileBuilder çıktıları lisans merkeziyle paketlenebilir.</p><a class="ao-content-btn secondary" href="<?= url('marketplace') ?>">Marketplace →</a></article>
      <article class="ao-content-card ao-service-card"><div class="ao-content-list-icon">💰</div><h3>Teklif Alın</h3><p>Özel mobil uygulama için hemen teklif alın.</p><a class="ao-content-btn secondary" href="<?= url('teklif') ?>">Teklif Talep Et →</a></article>
  </div>
  <div class="ao-content-cta"><h2>Projenizi Ahost One ekosistemine taşıyın</h2><p>Domain, hosting, ürün, teklif, müşteri paneli ve destek süreçleri aynı tasarım diliyle çalışır.</p><div class="ao-content-actions"><a class="ao-content-btn" href="<?= url('teklif') ?>">Teklif Al</a><a class="ao-content-btn secondary" href="<?= url('urunler') ?>">Ürünleri Gör</a></div></div>
</div></section>