
<?php ao_schema_ensure_v1400(); $projects=db()->query('SELECT * FROM sitebuilder_projects ORDER BY id DESC LIMIT 12')->fetchAll(); $pages=db()->query('SELECT p.*, pr.name project_name FROM sitebuilder_pages p LEFT JOIN sitebuilder_projects pr ON pr.id=p.project_id ORDER BY p.updated_at DESC LIMIT 12')->fetchAll(); ?>
<div class="ao-card ao-hero-card"><span class="ao-kicker">Ahost One v25.0.0 RC5</span><h2>SiteBuilder Pro</h2><p>Canlı sürükle-bırak sayfa oluşturma, tema entegrasyonu, header/footer/form/popup builder ve ZIP dışa aktarma. Müşteriler için de SiteBuilder erişimi.</p><div class="ao-actions">
    <a class="ao-btn" href="<?= url('admin/site-builder/pages') ?>">📄 Sayfalar</a>
    <a class="ao-btn primary" href="<?= url('admin/site-builder/live-editor') ?>">🎨 Live Builder</a>
    <a class="ao-btn secondary" href="<?= url('admin/site-builder/editor') ?>">⚡ Klasik Builder</a>
    <a class="ao-btn soft" href="<?= url('admin/site-builder/exports') ?>">📦 Export ZIP</a>
</div></div>
<div class="ao-grid two"><div class="ao-card"><h3>Projeler</h3><div class="sb-card-list"><?php foreach($projects as $p): ?><div class="sb-template"><strong><?= e($p['name']) ?></strong><p><?= e($p['type']) ?> · <?= e($p['status']) ?></p><a class="ao-btn soft" href="<?= url('admin/site-builder/pages?project_id='.$p['id']) ?>">Sayfalar</a></div><?php endforeach; ?></div></div><div class="ao-card"><h3>Son Sayfalar</h3><table class="ao-table"><tr><th>Sayfa</th><th>Proje</th><th>İşlem</th></tr><?php foreach($pages as $pg): ?><tr><td><?= e($pg['title']) ?></td><td><?= e($pg['project_name']) ?></td><td><a href="<?= url('admin/site-builder/live-editor?id='.$pg['id']) ?>">🎨 Live</a> · <a href="<?= url('admin/site-builder/editor?id='.$pg['id']) ?>">Klasik</a> · <a target="_blank" href="<?= url('sitebuilder/preview?id='.$pg['id']) ?>">Önizle</a></td></tr><?php endforeach; ?></table></div></div>
<div class="ao-card"><h3>Live Builder Özellikleri</h3><ul><li>🎨 Sürükle-bırak ile öğe ekleme</li><li>📐 Boyutlandırma ve stil değiştirme</li><li>↩ Geri al / Yinele desteği</li><li>📱 Canlı önizleme</li><li>👥 Müşteri panelinde SiteBuilder erişimi</li><li>📦 Site ZIP export motoru</li></ul></div>
